name: Lint and Format

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: astral-sh/ruff-action@v3
       with:
         args: "--version"
     - run: ruff check --output-format=github
     - run: ruff format --check --diff